# Change these first
owner: ArpaRec # Your GitHub organization or username, where this repository lives
repo: echo-status-page # The name of this repository

sites:
  - name: nz1
    check: "tcp-ping"
    url: 147.185.221.16
    port: 25871
  - name: nz2
    check: "tcp-ping"
    url: 147.185.221.16
    port: 45652
  - name: us1
    check: "tcp-ping"
    url: 169.254.65.98
    port: 6803

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: echostatus.arparec.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://mae.arparec.xyz/images/img_logo_icon_white_square.png
  name: EchoVR Status
  introTitle: "Status of custom EchoVR servers"
  introMessage: This page keeps a live status update of all custom EchoVR servers.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
